## Sarsa equations
- $Q(s_{t},a_{t}) = Q(s_{t},a_{t}) + \alpha (r_{t+1}+\gamma Q(s_{t+1},a_{t+1})-Q(s_{t},a_{t}))$

Based on
https://www.geeksforgeeks.org/sarsa-reinforcement-learning/

- `learning_rate` = $\alpha$
- `discount_rate` = $\gamma$

- `exploration_rate` = $\epsilon$
- `max_exploration_rate` = $\max(\epsilon)$
- `min_exploration_rate` = $\min(\epsilon)$
- `exploration_decay_rate` = $\epsilon$ decay rate

Step 1: Importing the required libraries

In [3]:
import numpy as np
import gymnasium as gym
import random
import time
from IPython.display import clear_output

Step 2: Building the environment

In [4]:
#Building the environment
env = gym.make('FrozenLake-v1')

Step 3: Initializing different parameters

In [5]:
#Defining the different parameters
exploration_rate = 0.8
num_episodes = 10000
max_steps_per_episode = 100
learning_rate = 0.85
discount_rate = 0.95

action_space_size = env.action_space.n
state_space_size = env.observation_space.n

q_table = np.zeros((state_space_size,action_space_size))
print(q_table)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


Step 4: Defining utility functions to be used in the learning process

In [11]:
#Function to choose the next action
def choose_action(state):
    action=0
    if np.random.uniform(0, 1) < exploration_rate:
        action = env.action_space.sample()
    else:
        action = np.argmax(Q[state, :])
    return action

#Function to learn the Q-value
def choose_action(state):
    if random.uniform(0, 1) < exploration_rate:
        action = env.action_space.sample()
    else:
        action = np.argmax(q_table[state, :])
    return action

Step 5: Training the learning agent

In [12]:
# Initializing the reward
rewards_all_episodes = []

# Starting the SARSA learning
for episode in range(num_episodes):

    state1, info = env.reset()
    action1 = choose_action(state1)
    done = False
    rewards_current_episode = 0

    for step in range(max_steps_per_episode):

        # Getting the next state
        state2, reward, terminated, truncated, info = env.step(action1)
        done = terminated or truncated

        # Choosing the next action
        action2 = choose_action(state2)

        # Learning the Q-value
        update(state1, state2, reward, action1, action2)

        state1 = state2
        action1 = action2

        # Updating the respective values
        rewards_current_episode += reward

        # If at the end of learning process
        if done:
            break

    rewards_all_episodes.append(rewards_current_episode)

# Calculate and print the average reward per thousand episodes
rewards_per_thousand_episodes = np.split(np.array(rewards_all_episodes), num_episodes / 1000)
count = 1000

print("********Average reward per thousand episodes********\n")
for r in rewards_per_thousand_episodes:
    print(count, ": ", str(sum(r / 1000)))
    count += 1000

# Print updated Q-table
print("\n\n********Q-table********\n")
print(q_table)

********Average reward per thousand episodes********

1000 :  0.01900000000000001
2000 :  0.012000000000000004
3000 :  0.02000000000000001
4000 :  0.014000000000000005
5000 :  0.017000000000000008
6000 :  0.022000000000000013
7000 :  0.011000000000000003
8000 :  0.012000000000000004
9000 :  0.016000000000000007
10000 :  0.01800000000000001


********Q-table********

[[2.57765280e-04 2.16807025e-04 3.31420479e-05 3.71026624e-04]
 [1.07902167e-03 2.44450008e-04 1.99080049e-04 1.60868414e-03]
 [1.60159291e-04 5.42477911e-03 8.85014236e-03 1.58367415e-03]
 [4.16623921e-03 1.29801714e-03 1.36296573e-03 5.98163151e-03]
 [6.35636532e-05 1.03451520e-06 3.49376142e-04 5.66466794e-05]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [1.13134234e-02 2.91244578e-08 4.62086685e-02 1.57086838e-03]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [5.21842308e-03 4.27051460e-05 1.21092910e-03 2.41158438e-03]
 [1.19936797e-01 5.63559121e-03 6.39623079e-01 3.60030429e-03]
 

Step 6: Evaluating the performance

In [13]:
for episode in range(3):
    # initialize new episode params
    state = env.reset()
    done = False
    print("*****EPISODE ", episode+1, "*****\n\n\n\n")
    time.sleep(1)

    for step in range(max_steps_per_episode):        
        # Show current state of environment on screen
        clear_output(wait=True)
        env.render()
        time.sleep(0.3)
        # Choose action with highest Q-value for current state
        action = np.argmax(q_table[state,:])
        # Take new action
        new_state, reward, done, info = env.step(action)

        if done:
            clear_output(wait=True)
            env.render()
            if reward == 1:
                print("****You reached the goal!****")
                time.sleep(3)
            else:
                print("****You fell through a hole!****")
                time.sleep(3)
            clear_output(wait=True)
            break           

        # Set new state
        state = new_state

env.close()

c:\Users\matti\Projects\Northeastern\rl-practice\.venv\Lib\site-packages\gymnasium\envs\toy_text\frozen_lake.py:353: UserWarning: WARN: You are calling render method without specifying any render mode. You can specify the render_mode at initialization, e.g. gym.make("FrozenLake-v1", render_mode="rgb_array")
  gym.logger.warn(


IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices